import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Zen_Maru_Gothic } from 'next/font/google';
import "./globals.css";
import DesktopNavBar from "@/components/NavBar";

const cooperBlack = localFont({
  src: [{
    path: "./fonts/COOPBL.ttf",
    weight: '400',
    style: 'normal'
  }],
  variable: '--font-cooper-black'
});

const zenMaruGothic = Zen_Maru_Gothic({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700", "900"],
  variable: '--font-zen-maru-gothic'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/svg/logo.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cooperBlack.variable} ${zenMaruGothic.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <DesktopNavBar />
        {children}
      </body>
    </html>
  );
}
